"""Verify every text-anchored claim against the page-tagged PDF text; write claims_register.csv/.md.

Run:  python3 verify_claims.py      (exit code 1 if any anchor is not found on its cited page)
"""
import csv
import os
import re
import sys

from claims import CLAIMS, OFFSET, TEXT

HERE = os.path.dirname(os.path.abspath(__file__))
TEXT_DIR = os.path.join(HERE, "..", "papers", "text")


def norm(s):
    return re.sub(r"\s+", " ", s).strip()


def load_pages(fname):
    raw = open(os.path.join(TEXT_DIR, fname), encoding="utf-8").read()
    parts = re.split(r"===== PAGE (\d+) =====", raw)
    return {int(parts[i]): norm(parts[i + 1]) for i in range(1, len(parts), 2)}


def main():
    pages = {p: load_pages(f) for p, f in TEXT.items()}
    rows, failures = [], []
    for cid, paper, pdf_page, loc, claim, anchor, used in CLAIMS:
        printed = pdf_page + OFFSET[paper]
        if anchor is None:
            status = "VISUAL (image table, checked on rendered page)"
        elif norm(anchor) in pages[paper].get(pdf_page, ""):
            status = "VERIFIED (anchor found on page)"
        else:
            status = "NOT FOUND"
            failures.append(cid)
        rows.append([cid, paper, pdf_page, printed, loc, claim, anchor or "", status, used])

    header = ["claim_id", "paper", "pdf_page", "printed_page", "location", "claim", "verbatim_anchor", "status", "used_in"]
    with open(os.path.join(HERE, "claims_register.csv"), "w", encoding="utf-8", newline="") as f:
        w = csv.writer(f)
        w.writerow(header)
        w.writerows(rows)

    with open(os.path.join(HERE, "claims_register.md"), "w", encoding="utf-8") as f:
        f.write("# Claims Register (Phase 16: Source Traceability)\n\n")
        f.write("Generated by `verify_claims.py` from `claims.py`. Each anchor is matched (whitespace-normalised) "
                "against the extracted text of the cited PDF page. `VISUAL` = image-only table, verified on the rendered page.\n\n")
        n_ver = sum(r[7].startswith("VERIFIED") for r in rows)
        n_vis = sum(r[7].startswith("VISUAL") for r in rows)
        f.write(f"**{len(rows)} claims · {n_ver} text-verified · {n_vis} visually verified · {len(failures)} not found**\n\n")
        f.write("| ID | Paper | PDF p. | Printed p. | Location | Claim | Anchor | Status | Used in |\n|---|---|---|---|---|---|---|---|---|\n")
        for r in rows:
            f.write("| " + " | ".join(str(x).replace("|", "\\|") for x in r) + " |\n")

    print(f"{len(rows)} claims; failures: {failures or 'none'}")
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
