"""Corpus-level tallies used in FINAL_RESEARCH_GAP_REPORT.md. Run: python3 tally.py"""
import csv, os
rows = list(csv.DictReader(open(os.path.join(os.path.dirname(os.path.abspath(__file__)), "corpus_coding.csv"))))
disc = [r for r in rows if "disclosure" in r["construct"].lower() and r["construct"] != "General disclosure"]
def n(rs, col): return sum(r[col] == "1" for r in rs), sum(r[col] in ("0", "1") for r in rs)
out = []
def add(label, rs, col):
    k, m = n(rs, col); out.append((label, f"{k}/{m}", ", ".join(r["paper"] for r in rs if r[col] == "1")))
add("CAPM-based COE (all papers)", rows, "capm_coe")
add("Implied / ex-ante COE (all papers)", rows, "implied_or_exante_coe")
add("Negative COE values in sample", rows, "negative_coe_values")
add("Firm-FE estimate reported", rows, "firm_fe_estimate_reported")
add("Full year effects", rows, "full_year_effects")
add("Dynamic GMM", rows, "dynamic_gmm")
add("Quasi-experiment (DiD / event / RD)", rows, "quasi_experiment")
add("External instrument", rows, "external_iv")
add("Mechanism formally tested", rows, "mechanism_tested")
add("Moderator formally tested", rows, "moderator_tested")
add("Regulatory shock inside window, unused", rows, "reg_shock_inside_window_unused")
add("Headline claim not supported by own preferred estimate", rows, "headline_not_supported_by_preferred_estimate")
add("Explicit limitations section", rows, "explicit_limitations_section")
add("CSR/sustainability papers: binary item-count index", disc, "disclosure_binary_count")
add("CSR/sustainability papers: disclosure quality measured", disc, "disclosure_quality_measured")
add("CSR/sustainability papers: control for general disclosure", disc, "controls_general_disclosure")
add("Cost of debt studied (all papers)", rows, "studies_cod")
w = max(len(a) for a, _, _ in out)
for a, b, c in out: print(f"{a:<{w}}  {b:>5}  {c}")
with open(os.path.join(os.path.dirname(os.path.abspath(__file__)), "corpus_tallies.md"), "w") as f:
    f.write("# Corpus tallies (generated by tally.py from corpus_coding.csv)\n\n| Feature | Count | Papers |\n|---|---|---|\n")
    for a, b, c in out: f.write(f"| {a} | {b} | {c or '—'} |\n")
