"""Build every generated artifact from content/ (the single source of truth).

    python3 tools/build.py

Writes: exercises/{source,generated}/*.md, hints/*.md, solutions/*.md, debugging/*.md,
review/*.md, curriculum/modules/*.md, source-mapping/*.md, app/data.json, app/index.html
Expected outputs are COMPUTED by running each reference solution, never typed by hand.
"""
from __future__ import annotations

import json
import re
from collections import defaultdict
from pathlib import Path

import yaml

import content as C
import sqlcheck as S

ROOT = C.ROOT
GEN_NOTE = "<!-- GENERATED by tools/build.py from content/*.yaml. Edit the YAML, not this file. -->\n"


def w(path: Path, text: str):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)


def refs_md(refs):
    return ", ".join(f"[{C.ref_label(r)}](../sources/{r['file']}.txt) *“{r['quote']}”*" if r.get("quote")
                     else f"[{C.ref_label(r)}](../sources/{r['file']}.txt)" for r in refs)


def md_table(columns, rows, limit=12):
    if columns is None:
        return "_(no result set)_\n"
    if not rows:
        return "| " + " | ".join(columns) + " |\n|" + "---|" * len(columns) + "\n\n_(no rows)_\n"
    out = ["| " + " | ".join(str(c) for c in columns) + " |", "|" + "---|" * len(columns)]
    for r in rows[:limit]:
        out.append("| " + " | ".join("NULL" if v is None else str(v).replace("|", "\\|") for v in r) + " |")
    if len(rows) > limit:
        out.append(f"\n_… {len(rows) - limit} more rows ({len(rows)} total)_")
    return "\n".join(out) + "\n"


def expected_md(ex):
    out = S.reference_output(ex)
    if out is None:
        return "_Self-check: compare with the reference solution._\n"
    if "checks" in out:
        parts = []
        for c in out["checks"]:
            parts.append(f"`{c['query']}`\n")
            parts.append(f"```text\n{c['plan']}\n```\n" if "plan" in c else md_table(c["columns"], c["rows"]))
        return "After your SQL, the checker runs:\n\n" + "\n".join(parts)
    if out.get("error") and not out.get("rows"):
        return f"The statement must fail with:\n```text\n{out['error']}\n```\n"
    return md_table(out["columns"], out["rows"])


def kind_label(ex):
    return {"query": "write a query", "modify": "change the database", "error": "trigger an error",
            "injection": "supply an input", "selfcheck": "self-check (not auto-graded)"}[ex["kind"]]


def exercise_header(ex, link_prefix="../"):
    badge = C.ORIGINS[ex["origin"]]
    stars = "★" * ex["difficulty"]
    eng = f" · engine **{ex['engine']}**" if ex.get("engine") else ""
    return (f"### {ex['id']} · {ex['title']}\n\n"
            f"> **{badge}**  \n"
            f"> Source: {refs_md(ex['source'])}\n\n"
            f"| Topic / concepts | Difficulty | Skills | Dataset | Task type |\n|---|---|---|---|---|\n"
            f"| {', '.join(ex['concepts'])} | {stars} | {', '.join(map(str, ex.get('skills', [])))} | "
            f"`{ex.get('db') or 'empty database'}` | {kind_label(ex)}{eng} |\n\n")


def build_exercise_pages(exs, mods):
    by_mod = defaultdict(list)
    for e in exs:
        by_mod[e["module"]].append(e)
    for m, items in by_mod.items():
        title = mods[m]["title"]
        for bucket, keep in (("source", lambda e: e["origin"] != "generated"),
                             ("generated", lambda e: e["origin"] == "generated")):
            sel = [e for e in items if keep(e)]
            head = (f"# {m} · {title}: {'SOURCE' if bucket == 'source' else 'GENERATED'} exercises\n\n" + GEN_NOTE +
                    ("These exercises come **from the lectures**: demonstrations to reproduce, questions the instructor asked, "
                     "or tasks explicitly left to the learner.\n\n" if bucket == "source" else
                     "These exercises were **written for this system**. They are *not* from the lectures, but each one reinforces "
                     "a concept the lectures cover and cites where that concept appears.\n\n") +
                    f"Hints: [`../../hints/{m}.md`](../../hints/{m}.md) · Solutions: [`../../solutions/{m}.md`](../../solutions/{m}.md) · "
                    "Run interactively: `python3 tools/practice.py <ID>` or the web trainer.\n\n")
            if not sel:
                w(ROOT / "exercises" / bucket / f"{m}.md", head + "_None in this module._\n")
                continue
            body = []
            for e in sel:
                b = exercise_header(e, "../../").replace("](../sources", "](../../sources")
                b += e["prompt"].strip() + "\n\n"
                if e.get("setup"):
                    b += f"<details><summary>Setup the checker runs first</summary>\n\n```sql\n{e['setup'].strip()}\n```\n</details>\n\n"
                if e.get("template"):
                    b += f"Query template: `{e['template']}`\n\n"
                if e["kind"] != "selfcheck":
                    b += "<details><summary>Expected output (try first!)</summary>\n\n" + expected_md(e) + "\n</details>\n\n"
                b += "---\n"
                body.append(b)
            w(ROOT / "exercises" / bucket / f"{m}.md", head + "\n".join(body))


def build_hints_solutions(exs, dbg, mods):
    by_mod = defaultdict(list)
    for e in exs:
        by_mod[e["module"]].append(e)
    for d in dbg:
        by_mod[d["module"]].append(d)
    for m, items in by_mod.items():
        h = [f"# {m} · {mods[m]['title']}: progressive hints\n\n", GEN_NOTE,
             "Open one level at a time. **Hint 1** gives the conceptual direction, **Hint 2** the SQL technique, "
             "**Hint 3** the query structure, and the final level is in [`solutions/`](../solutions/).\n\n"]
        s = [f"# {m} · {mods[m]['title']}: reference solutions\n\n", GEN_NOTE,
             "Try the exercise and its hints first. Every solution here is executed by `tests/test_system.py`.\n\n"]
        for e in items:
            h.append(f"## {e['id']} · {e['title']}\n\n")
            labels = ["Hint 1 · direction", "Hint 2 · technique", "Hint 3 · structure"]
            for lab, hint in zip(labels, e["hints"]):
                h.append(f"<details><summary>{lab}</summary>\n\n{hint}\n\n</details>\n\n")
            h.append(f"Final: [solution](../solutions/{m}.md#{e['id'].lower()}).\n\n")
            s.append(f"## {e['id']}\n\n**{e['title']}** · {C.ORIGINS[e['origin']]}  \nSource: "
                     + refs_md(e["source"]) + "\n\n")
            if e.get("broken"):
                s.append(f"Broken version:\n```sql\n{e['broken'].strip()}\n```\n\nFixed:\n")
            lang = "sql" if e.get("kind") != "injection" else "text"
            if e.get("kind") == "injection":
                s.append(f"Input to type (template `{e['template']}`):\n")
            s.append(f"```{lang}\n{e['solution'].strip()}\n```\n\n")
            if e.get("diagnosis"):
                s.append(f"**Diagnosis ({e['bug_type']}):** {e['diagnosis'].strip()}\n\n")
            if e.get("explanation"):
                s.append(f"**Why:** {e['explanation'].strip()}\n\n")
            if e.get("kind") not in (None, "selfcheck"):
                s.append("<details><summary>Expected output</summary>\n\n" + expected_md(e) + "\n</details>\n\n")
        w(ROOT / "hints" / f"{m}.md", "".join(h))
        w(ROOT / "solutions" / f"{m}.md", "".join(s))


def build_debugging(dbg, mods):
    by_mod = defaultdict(list)
    for d in dbg:
        by_mod[d["module"]].append(d)
    idx = ["# Debugging & error training\n\n", GEN_NOTE,
           "Each item gives you a **broken** query. Diagnose it (the bug type is hidden until the end), then fix it. "
           "Every broken query is *proven* wrong by the tests, and every fix is executed.\n\n"
           "No window-function items exist: window functions are not in the source material.\n\n",
           "| ID | Module | Title | Bug type | Origin |\n|---|---|---|---|---|\n"]
    for d in dbg:
        idx.append(f"| [{d['id']}]({d['module']}.md#{d['id'].lower()}) | {d['module']} | {d['title']} | {d['bug_type']} | "
                   f"{'SOURCE' if d['origin'] != 'generated' else 'GENERATED'} |\n")
    w(ROOT / "debugging" / "README.md", "".join(idx))
    for m, items in by_mod.items():
        out = [f"# {m} · {mods[m]['title']}: debugging\n\n", GEN_NOTE]
        for d in items:
            out.append(exercise_header(d).replace("### ", "## ", 1))
            out.append(d["prompt"].strip() + "\n\n")
            if d.get("setup"):
                out.append(f"<details><summary>Setup</summary>\n\n```sql\n{d['setup'].strip()}\n```\n</details>\n\n")
            out.append(f"```sql\n{d['broken'].strip()}\n```\n\n")
            out.append(f"<details><summary>Bug type</summary>\n\n`{d['bug_type']}`\n</details>\n\n")
            out.append(f"Hints → [`hints/{m}.md`](../hints/{m}.md#{d['id'].lower()}) · Fix → [`solutions/{m}.md`](../solutions/{m}.md#{d['id'].lower()})\n\n---\n")
        w(ROOT / "debugging" / f"{m}.md", "".join(out))


def predict_output(it):
    c = S.fresh_db(it.get("db"))
    if it.get("setup"):
        c.executescript(it["setup"])
    return S.format_result(S.run_script(c, it["sql"]), it["sql"])


def build_review(rev, mods, all_items):
    by_mod = defaultdict(list)
    for it in rev:
        by_mod[it["module"]].append(it)
    labels = {"quick": "Quick review", "concept": "Concept check", "predict": "Predict the output",
              "debug": "Debugging", "write": "Query writing"}
    for m, items in by_mod.items():
        out = [f"# {m} · {mods[m]['title']}: review deck\n\n", GEN_NOTE,
               "Spaced schedule: see [`curriculum/roadmap.md`](../curriculum/roadmap.md#spaced-review-plan). "
               "Answers are hidden. *Predict-the-output* answers were verified by executing the SQL.\n\n"]
        for it in items:
            out.append(f"### {it['id']} · {labels[it['type']]}\n\n")
            if it["type"] == "quick":
                out.append(f"{it['front']}\n\n<details><summary>Answer</summary>\n\n{it['back']}\n</details>\n\n")
            elif it["type"] in ("concept", "predict"):
                if it["type"] == "predict":
                    out.append(f"Dataset `{it.get('db') or 'empty'}`" + (" after setup:" if it.get("setup") else ":") + "\n\n")
                    if it.get("setup"):
                        out.append(f"```sql\n{it['setup'].strip()}\n```\n")
                    out.append(f"```sql\n{it['sql'].strip()}\n```\nWhat is printed?\n\n")
                else:
                    out.append(f"{it['question']}\n\n")
                for i, ch in enumerate(it["choices"]):
                    out.append(f"{chr(65 + i)}. `{ch}`\n" if it["type"] == "predict" else f"{chr(65 + i)}. {ch}\n")
                out.append(f"\n<details><summary>Answer</summary>\n\n**{chr(65 + it['answer'])}**. {it['why']}\n</details>\n\n")
            else:
                ref = all_items[it["ref"]]
                folder = "debugging" if it["type"] == "debug" else ("exercises/source" if ref["origin"] != "generated" else "exercises/generated")
                out.append(f"Do [{ref['id']} · {ref['title']}](../{folder}/{ref['module']}.md) without hints.\n\n")
            if it.get("source"):
                out.append(f"<sub>Source: {refs_md([it['source']])}</sub>\n\n")
        w(ROOT / "review" / f"{m}.md", "".join(out))


def concept_sources():
    """Parse concept → source ranges from curriculum/knowledge_map.md (hand-written)."""
    km = (ROOT / "curriculum" / "knowledge_map.md").read_text()
    res = {}
    for line in km.splitlines():
        m = re.match(r"\| (C\d\.\d+) \| ([^|]+) \|", line)
        if m:
            cid, name = m.group(1), m.group(2).strip()
            cells = line.split("|")
            src = cells[-2]
            refs = []
            for lec, ranges in re.findall(r"(lecture\d)((?: L\d+(?:-\d+)?,?)+)", src):
                for r in re.findall(r"L(\d+(?:-\d+)?)", ranges):
                    refs.append({"file": lec, "lines": r})
            res[cid] = {"name": name, "refs": refs}
    return res


def build_source_mapping(exs, dbg, rev, concepts):
    out = ["# Source → concept mapping\n\n", GEN_NOTE,
           "Every concept, exercise, debugging item and review card points back to transcript lines. "
           "`tests/test_system.py` checks that each line range exists **and** that the quoted words appear in it.\n\n"
           "| Short name | Original upload |\n|---|---|\n"]
    for k, v in C.SOURCE_FILES.items():
        out.append(f"| `{k}` ({C.LECTURE_TITLES[k]}) | `{v}` |\n")
    items_by_file = defaultdict(list)
    for cid, c in concepts.items():
        for r in c["refs"]:
            items_by_file[r["file"]].append((int(r["lines"].split("-")[0]), r["lines"], f"**{cid}** {c['name']}", "concept"))
    for e in exs + dbg:
        for r in e["source"]:
            kind = "debug" if e["id"].startswith("D") else ("exercise · " + e["origin"])
            items_by_file[r["file"]].append((int(str(r["lines"]).split("-")[0]), str(r["lines"]), f"{e['id']} {e['title']}", kind))
    for it in rev:
        if it.get("source"):
            r = it["source"]
            items_by_file[r["file"]].append((int(str(r["lines"]).split("-")[0]), str(r["lines"]), it["id"], "review"))
    for f in C.SOURCE_FILES:
        out.append(f"\n## {f} · {C.LECTURE_TITLES[f]}\n\n| Lines | Item | Kind |\n|---|---|---|\n")
        for _, lines, label, kind in sorted(items_by_file[f]):
            out.append(f"| [L{lines}](../sources/{f}.txt) | {label} | {kind} |\n")
    w(ROOT / "source-mapping" / "source_to_concept.md", "".join(out))

    c2 = ["# Concept → sources, lessons and practice\n\n", GEN_NOTE,
          "| Concept | Source lines | Exercises | Debugging |\n|---|---|---|---|\n"]
    for cid, c in concepts.items():
        ex_ids = [e["id"] for e in exs if cid in e["concepts"]]
        d_ids = [d["id"] for d in dbg if cid in d["concepts"]]
        c2.append(f"| **{cid}** {c['name']} | {', '.join(r['file'] + ' L' + r['lines'] for r in c['refs'])} | "
                  f"{', '.join(ex_ids) or '·'} | {', '.join(d_ids) or '·'} |\n")
    w(ROOT / "source-mapping" / "concept_index.md", "".join(c2))

    e2 = ["# Exercise index (all items, with origin labels)\n\n", GEN_NOTE,
          "| ID | Title | Origin | Kind | Source |\n|---|---|---|---|---|\n"]
    for e in exs + dbg:
        e2.append(f"| {e['id']} | {e['title']} | {e['origin'].upper()} | {e['kind']} | "
                  f"{'; '.join(C.ref_label(r) for r in e['source'])} |\n")
    w(ROOT / "source-mapping" / "exercise_index.md", "".join(e2))


def build_modules(mods, exs, dbg, rev, concepts):
    for m, mod in mods.items():
        ex_m = [e for e in exs if e["module"] == m]
        concept_ids = sorted({c for e in ex_m for c in e["concepts"] if c.startswith(f"C{m[1]}.")},
                             key=lambda x: int(x.split(".")[1]))
        concept_ids = [c for c in concepts if c.startswith(f"C{m[1]}.")]
        mistakes_src = (ROOT / "curriculum" / "knowledge_map.md").read_text()
        lines = [f"# Module {m} · {mod['title']}\n\n", GEN_NOTE,
                 f"**Source:** {mod['sources']} · **Lesson:** [{mod['lesson']}](../../{mod['lesson']}) · "
                 f"**Prerequisites:** {', '.join(mod['prerequisites'])}\n\n",
                 "## 1. Learning objectives\n\n" + "".join(f"- {o}\n" for o in mod["objectives"]) + "\n",
                 "## 2. Concepts\n\n| ID | Concept | Source |\n|---|---|---|\n"]
        for cid in concept_ids:
            c = concepts[cid]
            lines.append(f"| {cid} | {c['name']} | {', '.join(r['file'] + ' L' + r['lines'] for r in c['refs'])} |\n")
        lines.append(f"\n## 3. Prerequisites\n\n{', '.join(mod['prerequisites'])}; see the dependency graph in [roadmap.md](../roadmap.md).\n\n")
        lines.append(f"## 4-5. Explanation and examples\n\nIn [{mod['lesson']}](../../{mod['lesson']}): every concept at three levels "
                     "(intuition, SQL, practical reasoning) with the lecture's own examples.\n\n")
        lines.append("## 6. Common mistakes\n\n")
        for cid in concept_ids:
            for row in mistakes_src.splitlines():
                if row.startswith(f"| {cid} |"):
                    cells = [x.strip() for x in row.split("|")]
                    lines.append(f"- **{cid}**: {cells[8]}\n")
        lines.append("\n## 7. Practice exercises\n\n| ID | Title | Origin | ★ |\n|---|---|---|---|\n")
        for e in ex_m:
            folder = "source" if e["origin"] != "generated" else "generated"
            lines.append(f"| [{e['id']}](../../exercises/{folder}/{m}.md) | {e['title']} | {e['origin'].upper()} | {'★' * e['difficulty']} |\n")
        lines.append("\n## 8. Challenge exercises\n\n" + "".join(
            f"- {c} · {next(e['title'] for e in exs if e['id'] == c)}\n" for c in mod["challenge"]))
        d_m = [d for d in dbg if d["module"] == m]
        lines.append("\nDebugging: " + ", ".join(f"[{d['id']}](../../debugging/{m}.md)" for d in d_m) + "\n\n")
        lines.append(f"## 9. Review questions\n\n[review/{m}.md](../../review/{m}.md) ({sum(1 for r in rev if r['module'] == m)} cards)\n\n")
        lines.append("## 10. Mastery criteria\n\n" + "".join(f"- [ ] {x}\n" for x in mod["mastery"]))
        w(ROOT / "curriculum" / "modules" / f"{m}.md", "".join(lines))


def excerpt(ref, pad=0):
    a, _, b = str(ref["lines"]).partition("-")
    a, b = int(a), int(b or a)
    lines = C.source_lines(ref["file"])
    b = min(b, a + 40)
    return "\n".join(f"{i:>4}  {lines[i - 1]}" for i in range(a, b + 1))


def build_app_data(mods, exs, dbg, rev, concepts):
    def with_excerpts(refs):
        return [dict(r, lines=str(r["lines"]), text=excerpt(r)) for r in refs]

    def pack(e):
        d = {k: e[k] for k in e if k not in ("source",)}
        d["source"] = with_excerpts(e["source"])
        d["origin_label"] = C.ORIGINS[e["origin"]]
        if e["kind"] != "selfcheck":
            d["expected"] = S.reference_output(e)
        return d

    data = {
        "modules": [dict(id=m, **{k: v for k, v in mod.items()},
                         lesson_md=(ROOT / mod["lesson"]).read_text()) for m, mod in mods.items()],
        "exercises": [pack(e) for e in exs],
        "debugging": [pack(d) for d in dbg],
        "review": [dict(it, source=with_excerpts([it["source"]]) if it.get("source") else []) for it in rev],
        "datasets": {name: S.dataset_sql(name) for name in S.DATASETS},
        "concepts": concepts,
        "errata_md": (ROOT / "analysis" / "source-issues.md").read_text(),
        "roadmap_md": (ROOT / "curriculum" / "roadmap.md").read_text(),
    }
    js = json.dumps(data, ensure_ascii=False)
    w(ROOT / "app" / "data.json", js)
    tpl = (ROOT / "app" / "template.html").read_text()
    engine = (ROOT / "app" / "engine.js").read_text()
    page = tpl.replace("/*__ENGINE__*/", engine).replace("/*__DATA__*/null", js.replace("</", "<\\/"))
    # artifact.html: body content only (the publishing host adds doctype/head); index.html: full document for local use
    cdn = '<script src="https://cdn.jsdelivr.net/npm/sql.js@1.10.3/dist/sql-asm-memory-growth.js"></script>'
    w(ROOT / "app" / "artifact.html", page.replace('<script src="vendor/sql-asm.js"></script>', cdn))
    w(ROOT / "app" / "index.html", '<!doctype html>\n<html lang="en">\n<head>\n<meta charset="utf-8">\n'
      '<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">\n' + page + "\n</html>\n")


def main():
    mods = yaml.safe_load((C.CONTENT / "modules.yaml").read_text())
    exs, dbg, rev = C.exercises(), C.debugging(), C.review()
    concepts = concept_sources()
    all_items = {e["id"]: e for e in exs + dbg}
    build_exercise_pages(exs, mods)
    build_hints_solutions(exs, dbg, mods)
    build_debugging(dbg, mods)
    build_review(rev, mods, all_items)
    build_source_mapping(exs, dbg, rev, concepts)
    build_modules(mods, exs, dbg, rev, concepts)
    if (ROOT / "app" / "template.html").exists():
        build_app_data(mods, exs, dbg, rev, concepts)
    n_src = sum(e["origin"] != "generated" for e in exs + dbg)
    print(f"built: {len(exs)} exercises, {len(dbg)} debugging items, {len(rev)} review cards, "
          f"{len(concepts)} concepts; source-derived items: {n_src}, generated: {len(exs) + len(dbg) - n_src}")


if __name__ == "__main__":
    main()
