"""Single source of truth for the literature database.

Run:  python3 build_database.py
Writes literature_database.json and literature_matrix.csv next to this file.

Page convention: "PDF p.X / p.Y" = page X of the PDF file / printed journal page Y.
Page maps:  P1 printed = PDF+58 | P2 printed = PDF+1255 | P3 printed = PDF+137
            P4 printed = PDF+3084 | P5 printed = PDF+85 (PDF p.1 is a cover sheet)
Every field was extracted from the PDFs in ../papers/. Items marked
"[INFERENCE]" are reviewer judgements, not statements made by the authors.
"""
import csv
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))

PAPERS = [
    {
        "id": "P1",
        "short_cite": "Le Thi Nhung (2024)",
        "file": "206fdb74-187-b5pdf-1711106205.pdf",
        "title": "Cong bo thong tin trach nhiem xa hoi va chi phi von co phan: bang chung thuc nghiem tu cac doanh nghiep Viet Nam "
                 "(Corporate Social Responsibility Disclosure and Cost of Equity Capital: Empirical Evidence from Vietnamese Enterprises)",
        "authors": ["Le Thi Nhung (Academy of Policy and Development)"],
        "year": 2024,
        "source": "Tap chi Khoa hoc Thuong mai (Journal of Trade Science), No. 187/2024, pp. 61-71 (Vietnamese)",
        "doi": "10.54404/JTS.2024.187V.05",
        "page_map": "printed page = PDF page + 58 (PDF pp.1-2 are the issue table of contents)",
        "language": "Vietnamese (English summary PDF p.13 / p.71)",
        "topic": "CSR disclosure and cost of equity",
        "research_question": "Does the level of CSR disclosure affect the cost of equity of Vietnamese listed firms? [PDF p.4 / p.62]",
        "abstract": "Panel of 93 VNR500 (2021) listed non-financial firms, 2014-2021; CAPM cost of equity; content-analysis CSR disclosure index; "
                    "firms with higher CSR disclosure scores have lower cost of equity. [PDF p.3 / p.61]",
        "keywords": ["disclosure", "cost of equity", "social responsibility"],
        "theory": ["Information asymmetry / disclosure-cost of capital (liquidity, estimation risk, public vs private information) [PDF p.5 / p.63]",
                   "Risk-reduction view of CSR vs over-investment/agency-cost view of CSR (presented, not tested against each other) [PDF p.4-5 / p.62-63]",
                   "Signalling invoked in conclusion [PDF p.12 / p.70]"],
        "hypotheses": ["H1: negative relation between CSR disclosure and cost of equity [PDF p.6 / p.64]"],
        "data_source": "Annual, sustainability and CSR reports (hand-coded); prices, VNINDEX and 1-year government bond yields from Investing.com [PDF p.6 / p.64]",
        "sample": "93 of the VNR500-2021 firms listed on HOSE/HNX, excl. finance/banking, with at least one annual/SD/CSR report and full audited FS 2014-2021; 744 firm-years [PDF p.6 / p.64]",
        "country": "Vietnam",
        "industry": "Non-financial, multi-industry",
        "period": "2014-2021",
        "dependent_vars": ["Re: CAPM cost of equity; Rf = 1-year government bond; annual beta vs VNINDEX; market risk premium = average 2014-2021 VNINDEX return minus 1-year bond [PDF p.6-7 / p.64-65]"],
        "independent_vars": ["CSRI: 0/1 coding of 33 items derived from Circular 155/2015/TT-BTC (environment 18, labour 10, community 5), score/33 [Table 1, PDF p.7-8 / p.65-66]"],
        "moderators": [],
        "mediators": [],
        "controls": ["GROWTH (revenue growth)", "SIZE (ln total assets)", "LEV (liabilities/assets)", "BTM (book-to-market) [Table 2, PDF p.8 / p.66]"],
        "method": "Pooled OLS, FEM, REM; Hausman (p=0.0002) and F-test (p=0.0001) select FEM; GLS reported as final model [Tables 6-8, PDF p.10-11 / p.68-69]",
        "econometric_model": "Re_it = b1 + b2*CSRI_it + bj*X_it + mu_i + e_it [PDF p.9 / p.67]",
        "main_findings": ["CSRI -6.012*** in GLS (N=744) [Table 8, PDF p.11 / p.69]",
                          "SIZE -2.230*, LEV +0.795***, BTM +2.134**, GROWTH n.s. [Table 8]",
                          "Mean Re 14.251%; mean CSRI 0.432 [Table 3, PDF p.9 / p.67]"],
        "direction_disclosure_COE": "Negative",
        "robustness": ["None reported beyond the switch from FEM to GLS"],
        "limitations_explicit": ["Examines only the aggregate CSR-disclosure effect [PDF p.13 / p.71]"],
        "future_research": ["Effects of specific CSR dimensions on cost of equity [PDF p.13 / p.71]"],
        "reviewer_flags": [
            "Table 3: reported SD of CSRI (4.172) and LEV (2.194) exceed their own min-max ranges (0.048-0.895; 0.218-0.839), which is arithmetically impossible [PDF p.9 / p.67]",
            "Table 7: heteroskedasticity p=0.2351 and autocorrelation p=0.3065 do not reject the nulls, yet the text says both problems are present and switches to GLS [PDF p.11 / p.69]",
            "Table 8: the figures in parentheses are unlabelled; CSRI (-0.09) cannot be a t-statistic consistent with *** [PDF p.11 / p.69]",
            "Text gives mean VIF 1.29; Table 5 gives 1.25 [PDF p.10 / p.68]",
            "The FEM coefficient on CSRI (the Hausman-preferred model) is never reported",
            "[INFERENCE] The 2014-2021 window is chosen as 'before and after Circular 155' [PDF p.6 / p.64], but no pre/post or DiD test is run",
            "[INFERENCE] A constant market risk premium means cross-sectional COE variation comes only from beta; year-to-year variation comes from the 1-year Rf",
            "[INFERENCE] Sampling on the 2021 VNR500 list is look-ahead/survivorship selection",
            "[INFERENCE] Disclosure for year t comes out in the annual report in t+1, while beta is estimated from year-t returns (timing mismatch)",
        ],
    },
    {
        "id": "P2",
        "short_cite": "Nguyen & Duong (2026)",
        "file": "ef2e1594-The-impact-of-sustainability-reporting-on-the-cost-of-capital-evidence-from-Vietnam-s-listed.pdf",
        "title": "The impact of sustainability reporting on the cost of capital: evidence from Vietnam's listed companies",
        "authors": ["Huu Cuong Nguyen", "Hien Khanh Duong (University of Economics, The University of Da Nang)"],
        "year": 2026,
        "source": "Journal of Financial Reporting and Accounting, Vol. 24 No. 3, pp. 1256-1280 (Emerald); received Sep 2024, accepted Jan 2025",
        "doi": "10.1108/JFRA-09-2024-0642",
        "page_map": "printed page = PDF page + 1255",
        "language": "English",
        "topic": "GRI-based sustainability (SDG) disclosure and cost of debt, cost of equity and WACC",
        "research_question": "RQ1-RQ3: does sustainable-development disclosure affect COD, COE and WACC? [PDF p.3 / p.1258]",
        "abstract": "Top-100 listed firms by market cap (31 Dec 2023), 2021-2023; sustainability disclosure is negatively related to COD, COE and WACC; "
                    "environmental SDG disclosures have the largest effect. [PDF p.1 / p.1256]",
        "keywords": ["Cost of capital", "Cost of debt", "Cost of equity", "Sustainability disclosure", "WACC"],
        "theory": ["Agency theory", "Signalling theory (declared the 'most foundational') [PDF p.5 / p.1260]", "Resource dependence theory",
                   "Legitimacy theory", "Stakeholder theory", "Institutional theory [PDF p.4-5 / p.1259-1260]"],
        "hypotheses": ["H1: SD disclosure negatively related to COE [PDF p.5 / p.1260]",
                       "H2: SD disclosure negatively related to COD [PDF p.6 / p.1261]",
                       "H3: SD disclosure negatively related to WACC [PDF p.6 / p.1261]"],
        "data_source": "Annual reports, FS, ESG and sustainability reports (hand-coded); beta and market risk premium from Vietstock; bond yields from the Ministry of Finance [PDF p.6-7 / p.1261-1262]",
        "sample": "100 largest listed firms by market capitalisation at 31 Dec 2023 (~90% of market cap), 2021-2023; 300 firm-years [PDF p.6 / p.1261]",
        "country": "Vietnam",
        "industry": "Multi-industry (exclusion of financial firms not stated)",
        "period": "2021-2023",
        "dependent_vars": ["COE: CAPM, Rf = 10-year government bond [PDF p.7 / p.1262]",
                           "COD: interest expense / total liabilities [PDF p.7 / p.1262]",
                           "WACC: book weights, effective tax rate [PDF p.8 / p.1263]"],
        "independent_vars": ["SDG: average of 77 binary GRI (2016) items [PDF p.8 / p.1263]",
                             "Sub-indices SDG-environment, SDG-economy, SDG-society [Table 6, PDF p.15 / p.1270]"],
        "moderators": [],
        "mediators": [],
        "controls": ["FSIZE", "LEV", "TobinQ", "CASH", "ROA", "AGE", "GOV (majority state dummy)", "IND (environmentally sensitive industry, NAICS)",
                     "COVID (=1 for 2021) [Table 1, PDF p.9 / p.1264]"],
        "method": "OLS, FEM, REM; F-test and Hausman; GLS to correct autocorrelation/heteroskedasticity [PDF p.7 / p.1262]",
        "econometric_model": "Y_it = b0 + b1*SDG_it + controls + e_it, Y in {COE, COD, WACC} [Eqs 1-3, PDF p.7 / p.1262]",
        "main_findings": ["COE: GLS -0.070** (t=-3.25); FEM -0.138* (t=-2.52) [Table 3, PDF p.11 / p.1266]",
                          "COD: GLS -0.029* (t=-2.46); FEM -0.025* [Table 4, PDF p.12 / p.1267]",
                          "WACC: GLS -0.033*** (t=-4.59); FEM -0.038 n.s. (t=-1.34) [Table 5, PDF p.13 / p.1268]",
                          "Environment sub-index significant for COE (-0.090***), COD (-0.013***) and WACC (-0.025***); social sub-index for COD and WACC only; economic n.s. [Table 6, PDF p.15 / p.1270]",
                          "GOV lowers COE (-0.014*); IND (ESI) lowers WACC (-0.015***) [Tables 3, 5]"],
        "direction_disclosure_COE": "Negative",
        "robustness": ["Decomposition by GRI dimension, labelled a 'robust test' [Table 6, PDF p.14-15 / p.1269-1270]"],
        "limitations_explicit": ["Consistency of the 77-item scoring across firms' reporting styles [PDF p.16 / p.1271]",
                                 "COD measured as interest/total debt rather than actual loan rates [PDF p.16 / p.1271]",
                                 "No lagged effects [PDF p.16 / p.1271]"],
        "future_research": ["Longer time frame; broader sample and industries; address endogeneity; lagged variables; alternative COE methods; actual loan rates [PDF p.16 / p.1271]",
                            "Religion and gender diversity [PDF p.17 / p.1272]"],
        "reviewer_flags": [
            "COE minimum is negative (-0.057) [Table 2, PDF p.10 / p.1265]",
            "WACC effect is insignificant within firms (FEM t=-1.34); significance comes from GLS [Table 5, PDF p.13 / p.1268]",
            "Table 4: the FEM and REM columns are identical to three decimals for every variable [PDF p.12 / p.1267]",
            "Table 4: OLS SDG coefficient (t=-2.48) carries no significance star [PDF p.12 / p.1267]",
            "The COVID dummy (=2021) is the only time control in a 3-year panel [Table 1, PDF p.9 / p.1264]",
            "Sample selected on end-2023 market cap, i.e. ex-post selection [PDF p.6 / p.1261]",
            "FSIZE-LEV correlation 0.7 [PDF p.10 / p.1265]",
            "[INFERENCE] The WACC regression on LEV is partly mechanical, since WACC is built from LEV-dependent weights",
        ],
    },
    {
        "id": "P3",
        "short_cite": "Bui et al. (2025)",
        "file": "5fd254be-uffile-upload-no-title32076.pdf",
        "title": "Tac dong cua cong bo thong tin phat trien ben vung toi chi phi su dung von chu so huu cua cac doanh nghiep cong nghiep nang luong tren TTCK Viet Nam "
                 "(The impact of sustainable disclosure on the cost of equity of energy enterprises on the Vietnamese stock market)",
        "authors": ["Bui Thi An Binh", "Nguyen Thi Thuy Duong", "Le Thi Kieu Linh", "Nguyen Ba Duc Manh", "Nguyen Huyen Thuong (National Economics University)"],
        "year": 2025,
        "source": "Tap chi Khoa hoc va Cong nghe Truong Dai hoc Cong nghiep Ha Noi (HaUI Journal of Science and Technology), Vol. 61 No. 6, pp. 138-146 (Vietnamese)",
        "doi": "10.57001/huih5804.2025.229",
        "page_map": "printed page = PDF page + 137",
        "language": "Vietnamese (English abstract PDF p.1 / p.138)",
        "topic": "GRI-based sustainability disclosure and cost of equity in the energy industry",
        "research_question": "What is the effect of sustainability disclosure on the cost of equity of listed energy firms? [PDF p.1-2 / p.138-139]",
        "abstract": "58 energy firms (HOSE, HNX, UPCOM), 2019-2023, 290 observations; sustainability disclosure has a positive effect on cost of equity, "
                    "attributed to short-run compliance and reporting costs. [PDF p.1 / p.138]",
        "keywords": ["Sustainable development", "information disclosure", "cost of equity capital", "energy industry enterprises"],
        "theory": ["Legitimacy theory", "Stakeholder theory [PDF p.3 / p.140]", "Disclosure-liquidity argument (Diamond & Verrecchia) [PDF p.2 / p.139]"],
        "hypotheses": ["H1: SD disclosure negatively affects cost of equity [PDF p.4 / p.141]"],
        "data_source": "FiinPro-X (financial data); hand-coded FS, annual and sustainability reports; Rf from Damodaran's website [PDF p.4-5 / p.141-142]",
        "sample": "58 energy firms on HOSE/HNX/UPCOM, 2019-2023, 290 firm-years (balanced) [PDF p.5 / p.142]",
        "country": "Vietnam",
        "industry": "Energy",
        "period": "2019-2023",
        "dependent_vars": ["RE: CAPM, Rf = nominal 10-year government bond yield (Damodaran), beta = cov/var vs market [PDF p.4 / p.141]"],
        "independent_vars": ["PTBVDN: average of 77 binary GRI items (15 of which appear in the Circular 155 appendix) [PDF p.4 / p.141]"],
        "moderators": [],
        "mediators": [],
        "controls": ["SIZE", "ROE", "QM (board size)", "KT (Big4 auditor)", "LEV [PDF p.4-5 / p.141-142]"],
        "method": "OLS, REM, FEM; F-test and Hausman (p=0.0000, FEM preferred); VIF, Wald, Wooldridge; robust SE and GMM said to be applied [PDF p.5-7 / p.142-144]",
        "econometric_model": "RE = b0 + b1*PTBVDN + b2*SIZE + b3*ROE + b4*QM + b5*KT + b6*LEV (no firm or year subscripts shown, no year effects) [PDF p.4 / p.141]",
        "main_findings": ["PTBVDN: OLS +10.98 (p=0.009); REM +10.23 (p=0.041); FEM +4.79 (p=0.452) [Table 3, PDF p.6 / p.143]",
                          "Authors conclude a positive effect [PDF p.6-7 / p.143-144]",
                          "Mean disclosure rises from 0.163 (2019) to 0.188 (2023); max 0.571 [Table 1, PDF p.5 / p.142]",
                          "Mean COE falls from 9.21% (2019) to 6.88% (2021), then rises to 11.72% (2023); negative minima [Table 2, PDF p.6 / p.143]"],
        "direction_disclosure_COE": "Positive (as claimed; insignificant in the Hausman-preferred FEM)",
        "robustness": ["Robust SE and GMM described as applied, but no results are reported [PDF p.7 / p.144]"],
        "limitations_explicit": ["No limitations section; disclosure quality and credibility are discussed as a practical issue [PDF p.7 / p.144]"],
        "future_research": ["Other industries; dividend growth model for COE; effect on cost of debt [PDF p.8 / p.145]"],
        "reviewer_flags": [
            "The headline positive effect is insignificant in the Hausman-preferred FEM (p=0.452); it is significant only in OLS and REM [Table 3, PDF p.6 / p.143]",
            "Robust/GMM estimates claimed but not shown [PDF p.7 / p.144]",
            "F-test described as choosing between OLS and REM [PDF p.5 / p.142]",
            "No year effects, while disclosure trends up and COE moves sharply with macro conditions [Tables 1-2]",
            "Negative COE observations [Table 2, PDF p.6 / p.143]",
            "[INFERENCE] Common upward trends in disclosure and COE over 2021-2023, with no year effects, can produce a positive pooled correlation",
        ],
    },
    {
        "id": "P4",
        "short_cite": "Vu & Pham (2023)",
        "file": "8922477b-IJRPR20495.pdf",
        "title": "Research on the Impact of Governance Structure on the Cost of Equity Capital of Food Businesses Listed on the Vietnam Stock Market",
        "authors": ["Thuy Thi Thanh Vu", "Thuy Thi Pham (University of Labour and Social Affairs)"],
        "year": 2023,
        "source": "International Journal of Research Publication and Reviews, Vol. 4 No. 12, pp. 3085-3095",
        "doi": "10.55248/gengpi.4.1223.123524",
        "page_map": "printed page = PDF page + 3084",
        "language": "English",
        "topic": "Board and CEO governance structure and cost of equity",
        "research_question": "How does governance structure affect the cost of equity of listed food-processing firms? [PDF p.1 / p.3085]",
        "abstract": "55 listed food firms, 2015-2022; governance measured by board independence, CEO duality, CEO tenure, board meetings and nomination committee; "
                    "stronger governance lowers COE. [PDF p.1 / p.3085]",
        "keywords": ["Cost of Equity", "Corporate governance", "Listed enterprises"],
        "theory": ["Agency theory (Jensen & Meckling 1976)", "Stewardship theory, called 'management theory' (Davis et al. 1997), mentioned as the competing view [PDF p.9-10 / p.3093-3094]"],
        "hypotheses": ["H2-H12: expected signs in Table 1 (board size -, independence -, DUAL +, committee -, tenure -, meetings -) [PDF p.4 / p.3088]"],
        "data_source": "Annual reports (governance, hand-collected CEO tenure); FiinGroup (monthly prices); VNINDEX; 5- and 10-year bond yields [PDF p.2 / p.3086]",
        "sample": "55 food-processing listed firms, 2015-2022; 440 firm-years described, 341 used in regressions [PDF p.2, 6-9 / p.3086, 3090-3093]",
        "country": "Vietnam",
        "industry": "Food processing",
        "period": "2015-2022",
        "dependent_vars": ["COE: CAPM; Rf = 10-year bond; monthly rolling beta (12 observations), annualised [PDF p.2-3 / p.3086-3087]"],
        "independent_vars": ["BOARD.SIZE", "BOARDP (independent share)", "DUAL (coded 0 if CEO is chair, 1 if separate)", "TENURE", "MEET", "RENUMER (remuneration/nomination committee) [PDF p.2-4 / p.3086-3088]"],
        "moderators": [],
        "mediators": [],
        "controls": ["SIZE", "LIQUID (current ratio)", "GROWTH (market value growth)", "LEV", "ROA [PDF p.3 / p.3087]"],
        "method": "Pooled OLS, REM, FEM; BP-LM (p=0.3289), F-test (p=0.0000), Hausman (p=0.0211); Wald and Wooldridge; FE with clustered SE [PDF p.7-9 / p.3091-3093]",
        "econometric_model": "COE = a + b1 Size + b2 Liquid + b3 ROA + b4 Growth + b5 Boardp + b6 Dual + b7 Tenure + b8 Lev + b9 Meet + b10 Board.size + b11 Renumer + e [PDF p.4 / p.3088]",
        "main_findings": ["Final FE (clustered): BOARD.SIZE -0.064 (p=0.065), RENUMER -0.455 (p=0.083), DUAL +0.215 (p=0.077); BOARDP, TENURE, MEET n.s. [Table 8, PDF p.9 / p.3093]",
                          "SIZE -0.158 (p=0.083), ROA +2.27***, LEV +1.126**, GROWTH +0.294 (p=0.023) [Table 8]",
                          "R-squared 0.114, N=341 [Table 8]"],
        "direction_disclosure_COE": "n/a (governance study)",
        "robustness": ["None beyond model selection and clustering"],
        "limitations_explicit": ["None stated"],
        "future_research": ["None stated"],
        "reviewer_flags": [
            "DUAL = 1 means separate roles [PDF p.2 / p.3086], so the positive coefficient implies that separation raises COE; the paper reads it as 'duality raises COE' [PDF p.9 / p.3093]",
            "COE mean 0.38 with range -0.811 to 1.308 [Table 2, PDF p.5 / p.3089]",
            "440 observations described, 341 used, with no explanation",
            "Mean board size 5.748 [Table 2], but the text says the average is 7 [PDF p.10 / p.3094]",
            "GROWTH 95% CI [.542, .546] excludes its own coefficient .294 [Table 8, PDF p.9 / p.3093]",
            "'F test that all u_i=0: F(12,269)' implies 13 panel units, inconsistent with 55 firms [Table 5, PDF p.7 / p.3091] [INFERENCE on df]",
            "Interviews are mentioned as the basis for adding variables, but no interview method is described [PDF p.1 / p.3085]",
            "Of six governance variables only three are significant, and only at 10%; the conclusion of a general negative effect overstates the evidence",
        ],
    },
    {
        "id": "P5",
        "short_cite": "Le, Nguyen & Le (2019)",
        "file": "8a8e6b0c-The_impact_of_corporate_social_responsibility_on_t.pdf",
        "title": "The impact of corporate social responsibility on the cost of equity: an analysis of Vietnamese listed companies",
        "authors": ["Xuan Quynh Le", "Ngoc Tien Nguyen", "Thy Ha Van Le (Quy Nhon University)"],
        "year": 2019,
        "source": "Investment Management and Financial Innovations, 16(3), 87-96 (Business Perspectives)",
        "doi": "10.21511/imfi.16(3).2019.09",
        "page_map": "printed page = PDF page + 85 (PDF p.1 is a cover sheet)",
        "language": "English",
        "topic": "Environmental disclosure and ex-ante cost of equity",
        "research_question": "What is the effect of environmental disclosure on the cost of equity of Vietnamese listed firms? [PDF p.3 / p.88]",
        "abstract": "115 non-financial firms, 2014-2017, 460 observations; GRI content analysis; Easton (2004)-type ex-ante COE; FEM shows a significant negative relation. [PDF p.2 / p.87]",
        "keywords": ["environmental disclosure", "cost of equity", "impact", "FEM", "REM", "regression"],
        "theory": ["No formal theory section; social-contract/stakeholder information role of disclosure (Gray et al. 1995) [PDF p.3 / p.88]",
                   "Literature review lists explanations for positive findings: decoupling of disclosure and behaviour, negative-NPV CSR investment, lack of trust [PDF p.4 / p.89]"],
        "hypotheses": ["Environmental disclosure has a negative impact on cost of equity [PDF p.5 / p.90]"],
        "data_source": "Vietnamese annual reports (hand-coded); market data (source not specified) [PDF p.5-6 / p.90-91]",
        "sample": "115 non-financial listed firms each year 2014-2017 (460 firm-years); random sampling; food 26, aquatic 22, energy 14, others [Table 2, PDF p.5 / p.90]",
        "country": "Vietnam",
        "industry": "Non-financial, multi-industry",
        "period": "2014-2017",
        "dependent_vars": ["COE = forecast EPS(t+1) / average price after the report date (labelled an adjusted Easton 2004 PEG model) [PDF p.6 / p.91]"],
        "independent_vars": ["CED: environmental disclosure index, binary GRI (G4) items / expected items [PDF p.6 / p.91; PDF p.10 / p.95]"],
        "moderators": [],
        "mediators": [],
        "controls": ["SIZE", "LEV", "LTG (EPS growth)", "LIQUID", "SOE (% state)", "FOR (% foreign)", "BETA [Table 3, PDF p.7 / p.92]"],
        "method": "REM and FEM; Hausman (p=0.0055) selects FEM; Wald test; XTSCC (Driscoll-Kraay) SE [PDF p.8-9 / p.93-94]",
        "econometric_model": "COE_it = b0 + b1*CED_it + SIZE + LEV + LTG + LIQUID + SOE + FOR + BETA + e_it [Eq 3, PDF p.7 / p.92]",
        "main_findings": ["REM: CED -62.49 (t=-1.66, marked **) [Table 6, PDF p.8 / p.93]",
                          "FEM: CED -45.17 (t=-1.16, n.s.) [Table 6]",
                          "FEM with XTSCC SE: CED -45.17*** (t=-6.93) [Table 7, PDF p.9 / p.94]",
                          "SOE and FOR positive, LEV and BETA positive, SIZE negative under XTSCC [Table 7]",
                          "38 firms disclosed environmental information in 2014, 115 in 2017 [PDF p.8 / p.93]"],
        "direction_disclosure_COE": "Negative (significant only with Driscoll-Kraay SE)",
        "robustness": ["XTSCC standard errors only"],
        "limitations_explicit": ["Small sample (n=115), not highly representative [PDF p.10 / p.95]",
                                 "Non-financial firms only [PDF p.10 / p.95]",
                                 "GRI G4 criteria not all suited to Vietnam [PDF p.10 / p.95]"],
        "future_research": ["Build an environmental disclosure index on Circular 155 [PDF p.10 / p.95]"],
        "reviewer_flags": [
            "The text says REM shows a positive significant relation [PDF p.8 / p.93]; Table 6 shows a negative coefficient (-62.49)",
            "REM t=-1.66 is marked ** (5%) although |t| < 1.96 [Table 6]",
            "The coefficient goes from insignificant (t=-1.16) to t=-6.93 purely through the standard-error change, with T=4 [INFERENCE: Driscoll-Kraay SE are unreliable with very short T]",
            "The 'PEG' measure is in fact a forward earnings yield; COE mean 135.46, min -414.1, max 1015.3, units unclear [Table 4, PDF p.7 / p.92]",
            "The title says CSR, but only environmental disclosure is measured",
            "[INFERENCE] Disclosure rises from 38 to 115 disclosing firms across the Circular 155 effective period, so much of the CED variation is regulation-driven; this is not exploited",
        ],
    },
]

CSV_COLUMNS = [
    ("id", "Paper"), ("short_cite", "Citation"), ("year", "Year"), ("source", "Journal"), ("doi", "DOI"),
    ("research_question", "Research Question"), ("theory", "Theory"), ("data_source", "Data"), ("sample", "Sample"),
    ("industry", "Industry"), ("period", "Period"), ("independent_vars", "IV"), ("dependent_vars", "DV"),
    ("controls", "Controls"), ("method", "Method"), ("main_findings", "Main Finding"),
    ("direction_disclosure_COE", "Disclosure->COE sign"), ("limitations_explicit", "Limitation (explicit)"),
    ("reviewer_flags", "Reviewer flags"), ("future_research", "Future Research"), ("file", "File"),
]


def flat(v):
    return " | ".join(str(x) for x in v) if isinstance(v, list) else v


def main():
    with open(os.path.join(HERE, "literature_database.json"), "w", encoding="utf-8") as f:
        json.dump({"schema_note": __doc__.strip(), "papers": PAPERS}, f, ensure_ascii=False, indent=2)
    with open(os.path.join(HERE, "literature_matrix.csv"), "w", encoding="utf-8", newline="") as f:
        w = csv.writer(f)
        w.writerow([h for _, h in CSV_COLUMNS])
        for p in PAPERS:
            w.writerow([flat(p[k]) for k, _ in CSV_COLUMNS])
    print(f"Wrote {len(PAPERS)} papers")


if __name__ == "__main__":
    main()
