"""Batch 2 records (P6-P9) and duplicate-file log. Same schema as PAPERS in build_database.py.

Page maps:  P6 printed = PDF+1383 | P7 printed = PDF+63 | P8 no printed pages (online-first; PDF p.1 = cover)
            P9 printed = PDF+138
"""

DUPLICATES = [
    {
        "file": "0f2c53f6-IMFI_2019_03_Le.pdf",
        "duplicate_of": "P5",
        "batch": 2,
        "evidence": "Same article (Le, Nguyen & Le 2019, IMFI 16(3), 87-96, doi:10.21511/imfi.16(3).2019.09). "
                    "Whitespace-normalised extracted text is identical to P5's file except one added Web of Science "
                    "author link on the publisher cover sheet (PDF p.1). Not counted as a new paper.",
    }
]

BATCH2 = [
    {
        "id": "P6",
        "batch": 2,
        "short_cite": "Thuy, Khuong, Canh & Liem (2022)",
        "file": "c9acc018-thuy2022.pdf",
        "title": "The mediating effect of stock price crash risk on the relationship between corporate social responsibility and cost of equity "
                 "moderated by state ownership: Moderated-mediation analysis",
        "authors": ["Cao Thi Mien Thuy", "Nguyen Vinh Khuong", "Nguyen Thi Canh", "Nguyen Thanh Liem (University of Economics and Law, VNU-HCM)"],
        "year": 2022,
        "source": "Corporate Social Responsibility and Environmental Management, 29(5), 1384-1395 (Wiley); received Dec 2021, accepted Mar 2022",
        "doi": "10.1002/csr.2276",
        "page_map": "printed page = PDF page + 1383",
        "language": "English",
        "topic": "CSR disclosure and implied cost of equity: crash-risk mediation and state-ownership moderation",
        "research_question": "Does stock price crash risk mediate, and does state ownership moderate, the CSR disclosure-COE relation? [PDF p.2 / p.1385]",
        "abstract": "225 Vietnamese listed non-financial firms; GMM and Sobel tests; crash risk is a complementary mediator; abstract states that state ownership "
                    "strengthens the negative CSR-COE effect. [PDF p.1 / p.1384]",
        "keywords": ["corporate social responsibility", "cost of equity capital", "state ownership", "stock price crash risk"],
        "theory": ["Information asymmetry (Dhaliwal et al. 2011)", "Risk-management / idiosyncratic-risk view of CSR", "Investor base / socially conscious investors (Mohr et al.)",
                   "SOE multitask theory (Bai et al. 2006) vs SOE inefficiency [PDF p.2-3 / p.1385-1386]"],
        "hypotheses": ["H1: CSR disclosure negatively affects COE", "H2: crash risk mediates the CSR-COE relation",
                       "H3: state ownership moderates such that the negative relation is stronger when state ownership is higher [PDF p.3-4 / p.1386-1387]"],
        "data_source": "Annual and sustainable development reports (hand-coded CSR); Refinitiv Eikon (state ownership, financials); prices for crash risk [PDF p.4 / p.1387]",
        "sample": "225 non-financial firms with CSR disclosure data 2014-2019, 1,340 firm-years; industry leaders covering >=90% of industry assets; GMM N=816 [PDF p.4 / p.1387; Table 2]",
        "country": "Vietnam",
        "industry": "Non-financial, multi-industry (8 Refinitiv industry dummies)",
        "period": "2014-2019",
        "dependent_vars": ["COE: implied, Easton (2004) model with Harris & Wang (2013) cross-sectional earnings forecasts [PDF p.4 / p.1387; Appendix A, PDF p.12 / p.1395]",
                           "CRASH (stage-2 DV): DUVOL [PDF p.4-5 / p.1387-1388]"],
        "independent_vars": ["CSRD: 33 binary GRI-2016 criteria (6 economic, 8 environmental, 19 social) [PDF p.5 / p.1388]"],
        "moderators": ["SOE: % state ownership; mean-centred interaction CSRD x SOE [PDF p.5 / p.1388]"],
        "mediators": ["CRASH: stock price crash risk (DUVOL)"],
        "controls": ["SIZE", "LEV", "TANG", "ROA", "GROW", "AGE", "INDUSTRY dummies (no year effects reported) [PDF p.5 / p.1388]"],
        "method": "System GMM with lagged COE; Baron-Kenny three-step mediation; Sobel / delta / Monte Carlo tests; Hansen and AR(2) diagnostics [PDF p.5-8 / p.1388-1391]",
        "econometric_model": "COE_it = a + b*CSRD_it (+ g*CRASH_it) (+ SOE, CSRD x SOE) + controls + INDUSTRY + e_it [Eqs 1-7, PDF p.4 / p.1387]",
        "main_findings": ["CSRD -0.065*** on COE (t=-5.27), N=816 [Table 2, PDF p.7 / p.1390; signs verified on rendered page]",
                          "CSRD -0.204*** on CRASH; CRASH +0.142*** on COE; CSRD -0.067*** with CRASH included [Table 3, PDF p.8 / p.1391]",
                          "Sobel indirect effect -0.006 (p=0.029), 18.5% of total effect [Table 4, PDF p.8 / p.1391]",
                          "SOE -0.000***; INTERACTION +0.000*** (t=3.20) [Table 5, PDF p.9 / p.1392]",
                          "Mean COE 10.8%, mean CSRD 0.263 [Table 1, PDF p.6 / p.1389]"],
        "direction_disclosure_COE": "Negative",
        "robustness": ["Three Sobel variants (delta, Sobel, Monte Carlo) [Table 4]", "Hansen and AR(2) tests in every GMM column"],
        "limitations_explicit": ["Non-financial firms from one developing market; may not generalise across institutional settings [PDF p.10 / p.1393]"],
        "future_research": ["Replicate in other developing countries; state-owned firms in high-polluting industries; cross-national samples [PDF p.10 / p.1393]"],
        "reviewer_flags": [
            "Abstract and H3 say state ownership STRENGTHENS the negative CSR-COE effect [PDF p.1 / p.1384; PDF p.3-4 / p.1386-1387]; Table 5 shows a POSITIVE interaction with a negative main effect, i.e. attenuation, and the conclusion says 'attenuate' / 'mixed moderating role' [PDF p.9 / p.1392]",
            "The SOE and interaction coefficients are reported as 0.000, so economic magnitude cannot be assessed [Table 5]",
            "Adding the mediator makes the direct effect LARGER in magnitude (-0.065 to -0.067) [Table 3], which is inconsistent with a negative indirect path through CRASH",
            "The product of Table 3 paths (-0.204 x 0.142 = -0.029) does not match the Sobel indirect effect (-0.006), and Table 4's total/direct effects (0.033/0.027) do not match Table 3 (0.065/0.067)",
            "No year effects reported; the 2014-2019 window straddles Circular 155, which the paper calls 'the most essential document for regulating CSR in Vietnam' [PDF p.2 / p.1385] but does not exploit",
            "[INFERENCE] 100-120 instruments for 225 firms: below the groups count, but near the level where instrument proliferation weakens the Hansen test",
            "Negative-earnings firms are dropped from the Easton estimation [Appendix A], which is a selection on profitability",
        ],
    },
    {
        "id": "P7",
        "batch": 2,
        "short_cite": "Nguyen & Nguyen (2017)",
        "file": "1b16cfff-12231-42481-1-SM.pdf",
        "title": "Impact of Corporate Disclosure on Cost of Equity Capital in Vietnam",
        "authors": ["Dung Viet Nguyen", "Lan Thi Ngoc Nguyen (Foreign Trade University, Hanoi)"],
        "year": 2017,
        "source": "International Journal of Financial Research, 8(4), 64-70 (Sciedu Press)",
        "doi": "10.5430/ijfr.v8n4p64",
        "page_map": "printed page = PDF page + 63",
        "language": "English",
        "topic": "General (annual-report) corporate disclosure and implied cost of equity",
        "research_question": "Does disclosing more information reduce the cost of equity of firms listed in Vietnam? [PDF p.1 / p.64]",
        "abstract": "Botosan (1997) disclosure score and residual-income implied COE; disclosure has a significant reducing effect on COE. [PDF p.1 / p.64]",
        "keywords": ["disclosure", "cost of capital", "equity financing", "annual report score", "residual income valuation"],
        "theory": ["Adverse selection (Amihud & Mendelson; Diamond & Verrecchia)", "Estimation risk (Barry & Brown)",
                   "Public/private information structure (Easley & O'Hara 2004; Kim & Verrecchia) [PDF p.1-2 / p.64-65]"],
        "hypotheses": ["Implicit: disclosure lowers COE (no formal hypothesis numbering)"],
        "data_source": "FiinPro (StoxPlus): 2015 annual reports, accounting and price data [PDF p.4 / p.67]",
        "sample": "225 non-financial HOSE-listed firms, cross-section, financial year 2015 [PDF p.4 / p.67]",
        "country": "Vietnam",
        "industry": "Non-financial, multi-industry",
        "period": "2015 (cross-section)",
        "dependent_vars": ["IMPLIED: residual-income implied COE, 2-year horizon, self-generated forecasts (growth = ROE x plowback), prices 3 months after year-end [PDF p.3-4 / p.66-67]"],
        "independent_vars": ["DSCORE: Botosan (1997) annual-report disclosure index, 105 points [PDF p.2-4 / p.65-67]"],
        "moderators": [],
        "mediators": [],
        "controls": ["Beta (6-month daily)", "PB (market-to-book)", "LnMCAP [PDF p.4 / p.67]"],
        "method": "Cross-sectional OLS with White-Huber SE; stepwise and rank regression robustness [PDF p.5-6 / p.68-69]",
        "econometric_model": "IMPLIED_i = a + b1 DSCORE_i + b2 BETA_i + b3 PB_i + b4 LnMCAP_i + e_i [Eq 4, PDF p.5 / p.68]",
        "main_findings": ["DSCORE -0.0016*** (t=-4.33) [Table 3, PDF p.5 / p.68]",
                          "Beta insignificant (-0.0045, p=0.672); beta-implied COE correlation -0.0266 n.s. [Tables 2-3, PDF p.5 / p.68]",
                          "LnMCAP +0.0067** (size raises implied COE), attributed to mispricing [PDF p.5-6 / p.68-69]",
                          "Mean disclosure 27/105; mean implied COE 14.84% [Table 1, PDF p.4 / p.67]",
                          "Rank regression: rankDSCORE -0.2641*** [Table 4, PDF p.6 / p.69]"],
        "direction_disclosure_COE": "Negative",
        "robustness": ["Stepwise selection", "Rank regression (non-normal residuals) [PDF p.6 / p.69]"],
        "limitations_explicit": ["None stated as a section; notes that analyst forecasts are unavailable in Vietnam, so forecasts are self-generated [PDF p.3 / p.66]"],
        "future_research": ["None stated"],
        "reviewer_flags": [
            "Single-year cross-section; disclosure policy assumed 'quite stable over time' without evidence [PDF p.4 / p.67]",
            "[INFERENCE] Self-generated forecasts (ROE x plowback) tie the implied COE mechanically to profitability and payout, which may correlate with disclosure",
            "No endogeneity treatment; only three controls",
            "Explicitly argues CAPM cannot test a disclosure effect [PDF p.3 / p.66], which directly bears on P1-P4, P9",
        ],
    },
    {
        "id": "P8",
        "batch": 2,
        "short_cite": "Srivastava, Das & Pattanayak (2019)",
        "file": "f57fe841-srivastava2019.pdf",
        "title": "Impact of corporate governance attributes on cost of equity: Evidence from an emerging economy",
        "authors": ["Varnita Srivastava (Christ University)", "Niladri Das", "Jamini Kanta Pattanayak (IIT Dhanbad)"],
        "year": 2019,
        "source": "Managerial Auditing Journal (Emerald), online-first version (no volume/page numbers in the PDF)",
        "doi": "10.1108/MAJ-01-2018-1770",
        "page_map": "no printed page numbers; cite PDF pages (PDF p.1 = Emerald cover sheet)",
        "language": "English",
        "topic": "Composite corporate governance index and cost of equity (India)",
        "research_question": "Does a comprehensive Indian corporate governance index (post-Companies Act 2013) lower the cost of equity? [PDF p.2]",
        "abstract": "S&P BSE 500 firms 2001-2016; 43-attribute, 7-sub-index CGI; negative significant CGI-COE relation; board composition and audit committee sub-indices matter. [PDF p.2]",
        "keywords": ["India", "Corporate governance", "Corporate governance index", "Emerging market", "Cost of equity"],
        "theory": ["Agency theory (Jensen & Meckling 1976) [PDF p.2-3]", "Law-and-finance / investor protection (La Porta et al. 1998) [PDF p.7]"],
        "hypotheses": ["H1: corporate governance has a negative impact on the cost of equity [PDF p.7]"],
        "data_source": "CMIE ProwessIQ; hand-collected governance from annual reports [PDF p.8]",
        "sample": "319 non-financial S&P BSE 500 firms with March fiscal year-end, 2001-2016, 5,104 firm-years (balanced; missing data interpolated/extrapolated) [PDF p.8]",
        "country": "India",
        "industry": "Non-financial, multi-industry (20 sectors)",
        "period": "2001-2016",
        "dependent_vars": ["COE (%): MEASUREMENT NOT DEFINED anywhere in the paper (verified by full-text search)"],
        "independent_vars": ["CGI: 43 binary items scored 1 only if ABOVE the mandatory minimum; 7 equally weighted sub-indices (board composition, board activities, audit committee, "
                             "shareholders' grievance, nomination & remuneration, ownership structure, cross-listing) [PDF p.9, 11-13; Table I]"],
        "moderators": [],
        "mediators": [],
        "controls": ["Leverage", "Market-to-book", "Log assets", "Board size", "Sales growth", "Industry dummies [PDF p.11]"],
        "method": "Pooled OLS (Hausman p=0.0695 favours RE; BP-LM p=1.000 favours pooled OLS) [PDF p.15]",
        "econometric_model": "COE = a + b1 CGI + b2 Lever + b3 MTBR + b4 LogAssets + b5 BoardSize + b6 SaleGrowth + Industry + e [PDF p.11]",
        "main_findings": ["CGI -0.089 (p=0.021); R-squared 0.083 [Table III, PDF p.15; signs verified on rendered page]",
                          "Board composition -0.068 (p=0.036); audit committee -0.061 (p=0.035); ownership structure -0.130 (p=0.049); other sub-indices n.s. [Table III]",
                          "Only market-to-book significant among controls [PDF p.11]"],
        "direction_disclosure_COE": "n/a (governance study)",
        "robustness": ["CGI regressed on ROA and PE ratio (not a robustness test of the COE result) [PDF p.11; Table III]"],
        "limitations_explicit": ["None stated"],
        "future_research": ["Use the index to study other valuation and profitability measures [PDF p.18]"],
        "reviewer_flags": [
            "The dependent variable's construction is never described",
            "Claims a 'causal relationship' [PDF p.2] from pooled OLS",
            "Text credits 'fixed effects regression models' [PDF p.16] though pooled OLS is the reported model",
            "Missing data interpolated/extrapolated; index-replacement firms filled with prior constituents' data [PDF p.8]",
            "Ownership-structure sub-index is significant in Table III but not mentioned in the abstract or discussion",
            "Above-mandatory scoring [PDF p.9] is a design precedent for separating compliance from voluntary practice (relevant to G6/G13)",
        ],
    },
    {
        "id": "P9",
        "batch": 2,
        "short_cite": "Shah & Butt (2009)",
        "file": "a7eaed52-6_Zulfiqar_Shah2.pdf",
        "title": "The Impact of Corporate Governance on the Cost of Equity: Empirical Evidence from Pakistani Listed Companies",
        "authors": ["Syed Zulfiqar Ali Shah", "Safdar Ali Butt (Mohammad Ali Jinnah University, Islamabad)"],
        "year": 2009,
        "source": "The Lahore Journal of Economics, 14(1), 139-171",
        "doi": "Not shown in the PDF",
        "page_map": "printed page = PDF page + 138 (PDF metadata title is wrong: 'Apple market integration')",
        "language": "English",
        "topic": "Governance attributes and a governance score vs CAPM cost of equity (Pakistan)",
        "research_question": "Does corporate governance quality affect the cost of equity of Pakistani listed firms? [PDF p.2-3 / p.140-141]",
        "abstract": "114 KSE firms 2003-2007; CAPM COE; managerial ownership and board size negative; board independence, audit committee independence and the governance score positive. [PDF p.1 / p.139]",
        "keywords": ["Corporate governance", "cost of equity", "Pakistan"],
        "theory": ["Agency theory", "Signalling of investor protection (Himmelberg et al.) [PDF p.4-5 / p.142-143]",
                   "Investor-protection substitution/complementarity (Klapper & Love 2002; Chen et al. 2004) [PDF p.6, 8 / p.144, 146]"],
        "hypotheses": ["H0: governance does not affect cost of capital; H1: it does [PDF p.10 / p.148]"],
        "data_source": "Annual reports, State Bank of Pakistan balance-sheet review, company websites, direct contact [PDF p.9 / p.147]",
        "sample": "114 non-financial KSE firms across 15 sectors (57 textile spinning), 2003-2007; 541-558 obs [PDF p.9 / p.147; Tables 5-10]",
        "country": "Pakistan",
        "industry": "Non-financial, multi-industry (textile-dominated)",
        "period": "2003-2007",
        "dependent_vars": ["Ke: CAPM, beta from 2 years of monthly returns [PDF p.11 / p.149]"],
        "independent_vars": ["Individual: ownership concentration, managerial ownership, board independence, audit committee independence, board size",
                             "CGS: weighted score (INED presence 55%, ownership 45%) [Appendix B, PDF p.32 / p.170]"],
        "moderators": [],
        "mediators": [],
        "controls": ["Log total assets", "ROE [PDF p.10-11 / p.148-149]"],
        "method": "OLS; LSDV with industry dummies ('fixed effects') and with industry + year dummies [PDF p.12-22 / p.150-160]",
        "econometric_model": "Ke_it = a + b1 Fsize + b2 OC + b3 MO + b4 BI + b5 ACI + b6 BS + b7 ROE (+ industry, year dummies) + u_it [PDF p.13 / p.151]",
        "main_findings": ["OLS: only size significant (-0.0094, t=-3.24); R-squared 0.034 [Table 4, PDF p.13 / p.151]",
                          "Industry + year dummies: board size -0.017 (p=0.088); size -0.0078 (p=0.018); OC, MO, BI, ACI, ROE n.s. [Table 6, PDF p.17 / p.155]",
                          "CGS +0.0018 (p=0.913) and +0.0028 (p=0.855), n.s. [Tables 9-10, PDF p.20, 22 / p.158, 160]",
                          "Year dummies large and negative (2007: -0.287, p<0.001) [Table 6]"],
        "direction_disclosure_COE": "n/a (governance study)",
        "robustness": ["Alternative dummy structures only"],
        "limitations_explicit": ["Governance score limited by unavailability of published data on many governance aspects [PDF p.25 / p.163]"],
        "future_research": ["More variables in the governance score; estimate Ke with other models [PDF p.25 / p.163]"],
        "reviewer_flags": [
            "Conclusion 'good corporate governance reduces a company's cost of equity' [PDF p.25 / p.163] is not supported: the governance score is positive and insignificant, and only board size is marginal",
            "The discussion of managerial ownership contradicts itself ('negative impact ... i.e. higher ownership leads to higher COE') [PDF p.23 / p.161]",
            "Table 2 maximum and minimum rows are swapped; Ke ranges from -0.93 to 1.91 (negative CAPM COE again) [PDF p.11 / p.149]",
            "'Fixed effects' are industry dummies, not firm effects",
            "Measurement-validity insight: Pakistani firms label all non-executive directors as independent, so BI may carry no information [PDF p.23 / p.161]",
        ],
    },
]
